### ISSUE TITLE
installation from path or url cannot be constrained to a version

### ISSUE THREAD

**Issue by rudgr** [pjmaenh/home-assistant-vaillant#1]
hmmm, after upgrading to HA 0.94 the vaillant component fails to load:

`Unable to install package https://github.com/samueldumont/netatmo-api-python/archive/v1.4.1-vaillant.zip#pyatmo==1.4.1-vaillant: ERROR: Could not satisfy constraints for 'pyatmo': installation from path or url cannot be constrained to a version`

**Comment by rudgr** [comment]
tried: removing the "#pyatmo==1.4.1-vaillant" part of the url, but doesn't seem to help.

**Comment by pjmaenh** [comment]
Working on this - stay tuned

**Comment by pjmaenh** [comment]
Should be working now. It's a temporary fix, as I will be updating the pyatmo-vaillant library soon.

**Comment by rudgr** [comment]
awesome @pjmaenh !!! :) tx

**Comment by rudgr** [comment]
just wanted to confirm it works on HA v94.4 :) tx again
