### ISSUE TITLE
API_KEY and others

### ISSUE THREAD

**Issue by Acey-yo** [pjmaenh/home-assistant-vaillant#4]
Hello, 

I'm desperately trying to find the right keys that you described here (Replace <API_KEY>, <SECRET_KEY>, <APP_VERSION> and <USER_PREFIX> by the correct keys for either Vaillant or Bulex / Saunier Duval. The required values ​​can be retrieved by decompiling the official mobile app.)

Do you have a tip or could we possibly help?

Would be really great if you can help.

Thank you

**Comment by pjmaenh** [comment]
Please send me a private message (on GitHub or HA community) indicating what system you have (Vaillant, Bulex or Saunier Duval).

**Comment by drupol** [comment]
Also looking for help :)
