### ISSUE TITLE
ClimateDevice is deprecated

### ISSUE THREAD

**Issue by alexbelgium** [pjmaenh/home-assistant-vaillant#6]
Since : update to HA 0.110 
Error message : "ClimateDevice is deprecated, modify VaillantThermostat to extend ClimateEntity"
Impact : none that I see
Logger : homeassistant.components.climate
Source : components/climate/_init_.py:547

Thanks for your support for this great component

**Comment by alexbelgium** [comment]
Hi, I created a pull request to address the issue - please review it if you find it useful!

**Comment by pjmaenh** [comment]
Thanks for the PR, I just merged it - apologies it took some time!
